name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      linux:
        description: "Linux"
        type: boolean
        default: false
      macos:
        description: "macOS"
        type: boolean
        default: false
      windows:
        description: "Windows"
        type: boolean
        default: false
      stylua:
        description: "StyLua"
        type: boolean
        default: false
      luacheck:
        description: "Luacheck"
        type: boolean
        default: false
      markdownlint:
        description: "Markdownlint"
        type: boolean
        default: false
      tests:
        description: "Tests"
        type: boolean
        default: false
      docs:
        description: "Docs"
        type: boolean
        default: false
      release-please:
        description: "Release Please"
        type: boolean
        default: false
      publish-dev:
        description: "Publish dev"
        type: boolean
        default: false
      publish-release:
        description: "Publish release"
        type: boolean
        default: false
jobs:
  ci:
    uses: BlueLua/.github/.github/workflows/ci.yml@main
    secrets: inherit
    # prettier-ignore
    with:
      linux:   ${{ inputs.linux   || github.event_name != 'workflow_dispatch' }}
      macos:   ${{ inputs.macos   || github.event_name != 'workflow_dispatch' }}
      windows: ${{ inputs.windows || github.event_name != 'workflow_dispatch' }}

      stylua:       ${{ inputs.stylua       || false }}
      luacheck:     ${{ inputs.luacheck     || false }}
      markdownlint: ${{ inputs.markdownlint || false }}

      tests: ${{ inputs.tests || false }}
      docs:  ${{ inputs.docs  || false }}

      release-please:  ${{ inputs.release-please  || false }}
      publish-dev:     ${{ inputs.publish-dev     || false }}
      publish-release: ${{ inputs.publish-release || false }}
